class AppConstant {
  static List animation = [
    "assets/animation/Foggy.json",
    "assets/animation/Weather-cloudy(night).json",
    "assets/animation/Weather-mist.json",
    "assets/animation/Weather-partly cloudy.json",
    "assets/animation/Weather-partly shower.json",
    "assets/animation/Weather-snow sunny.json",
    "assets/animation/Weather-snow.json",
    "assets/animation/Weather-snow(night).json",
    "assets/animation/Weather-storm&showers(day).json",
    "assets/animation/Weather-sunny.json",
    "assets/animation/Weather-thunder.json",
    "assets/animation/Weather-windy.json",
    "assets/animation/Foggy.json",
    "assets/animation/Weather-cloudy(night).json",
    "assets/animation/Weather-mist.json",
    "assets/animation/Weather-partly cloudy.json",
    "assets/animation/Weather-partly shower.json",
    "assets/animation/Weather-snow sunny.json",
    "assets/animation/Weather-snow.json",
    "assets/animation/Weather-snow(night).json",
    "assets/animation/Weather-storm&showers(day).json",
    "assets/animation/Weather-sunny.json",
    "assets/animation/Weather-thunder.json",
    "assets/animation/Weather-windy.json",
  ];
  static List daysWeather = [
    "assets/animation/Weather-snow sunny.json",
    "assets/animation/Weather-snow.json",
    "assets/animation/Weather-snow(night).json",
    "assets/animation/Weather-storm&showers(day).json",
    "assets/animation/Weather-sunny.json",
    "assets/animation/Weather-thunder.json",
    "assets/animation/Weather-windy.json",
  ];
  static List typeWeather = [
    "snow sunny",
    "snow",
    "snow",
    "storm",
    "sunny",
    "thunder",
    "windy",
  ];
  static List hours = [
    "1:00",
    "2:00",
    "3:00",
    "4:00",
    "5:00",
    "6:00",
    "7:00",
    "8:00",
    "9:00",
    "10:00",
    "11:00",
    "12:00",
    "13:00",
    "14:00",
    "15:00",
    "16:00",
    "17:00",
    "18:00",
    "19:00",
    "20:00",
    "21:00",
    "22:00",
    "23:00",
    "24:00",
  ];

  static List temperature = [
    "16",
    "19",
    "20",
    "25",
    "23",
    "27",
    "22",
    "20",
    "15",
    "27",
    "28",
    "24",
    "29",
    "30",
    "14",
    "18",
    "22",
    "23",
    "25",
    "24",
    "22",
    "28",
    "26",
    "23",
  ];
  static List tempe = [
    "13",
    "12",
    "14",
    "17",
    "15",
    "14",
    "15",
    "13",
    "12",
    "16",
    "17",
    "14",
    "18",
    "19",
    "12",
    "13",
    "12",
    "16",
    "15",
    "13",
    "17",
    "20",
    "18",
    "14",
  ];
  static List days = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
}
